name: scalespacegan
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.3.1
  - pytorch=1.10.0
  - torchvision=0.11.0
  - numpy
  - pandas
  - jupyter
  - pip
  - tensorboard
  - tqdm
  - ipython
  - pillow
  - opencv
  - imageio
  - freetype-py
  - pyopengl
  - selenium
  - setuptools==59.5.0
  - mkl=2022.1.0
  - pip:
     - lpips
     - easydict
     - glfw
     - ninja
     - ipywidgets
     - ipyevents
     - click
     - chromedriver-autoinstaller
     - geemap
